export default function AdminTutorial() {
  const sections = [
    ["1. Connexion et sécurité", "Saisissez l’e-mail et le mot de passe administrateur puis cliquez sur « Se connecter ». Le bouton « Déconnexion » ferme la session. N’utilisez jamais un compte client pour administrer la boutique et ne partagez pas les clés API."],
    ["2. Commandes", "Utilisez les sous-onglets « À préparer », « Prêtes », « À expédier », « Expédiées » et « Annulées ». Cliquez sur « Voir détails » pour ouvrir une commande. Vérifiez les articles, quantités, poids, adresse, transporteur, point relais et options cadeau. Cliquez sur « À expédier » quand la préparation est terminée, puis saisissez le transporteur et le suivi dans la fenêtre d’expédition. Le bouton d’impression crée le bon de commande."],
    ["3. Articles", "Dans « Ajouter un article », remplissez les champs marqués d’un astérisque, choisissez la catégorie, renseignez prix, réduction, stock et poids en grammes, puis ajoutez les photos. Cliquez sur « Ajouter ». Dans la liste, utilisez « Rechercher par référence » et le filtre catégorie. Le bouton œil masque ou réactive l’article ; « Modifier » ouvre tous les champs ; la poubelle supprime définitivement l’article après confirmation."],
    ["4. Organisation du catalogue", "Dans chaque bloc (catégories, sous-catégories, thèmes, couleurs), écrivez une valeur puis cliquez sur « + ». L’œil masque ou affiche la valeur dans la boutique. La poubelle la supprime de la liste. Enregistrez avant de quitter. Une valeur supprimée ne supprime pas les anciens articles qui la contiennent."],
    ["5. Calendriers de l’Avent", "Pour un calendrier sur mesure, saisissez le titre, prix et stock, choisissez le nombre de cases, la finition et les catégories, cochez les options, ajoutez une image puis cliquez sur « Créer ». Pour un calendrier virtuel, définissez les dates, activez chaque case et indiquez type de réduction, valeur, code et montant minimum. Enregistrez ensuite la configuration."],
    ["6. Codes promo", "Saisissez le code, choisissez « Pourcentage » ou « Montant fixe », indiquez la valeur, le nombre maximal d’utilisations, la date d’expiration et le montant minimum. Cliquez sur « Créer le code ». Vérifiez la colonne statut ; supprimez un code uniquement s’il n’a jamais été utilisé."],
    ["7. Cartes cadeaux", "Pour une carte prédéfinie, indiquez le code et le montant puis cliquez sur « Créer ». Pour une carte sur mesure, créez un article et définissez le minimum et le maximum. Une carte virtuelle est envoyée automatiquement par e-mail ; une carte physique apparaît dans la commande avec l’adresse à préparer. La poubelle supprime une carte créée par erreur."],
    ["8. Livraison", "Le panier calcule automatiquement le poids total à partir des fiches articles. Le client choisit Mondial Relay, Colissimo relais ou Colissimo domicile ; le tarif s’affiche avant paiement. Pour un relais, il saisit son code postal, clique sur « Rechercher », puis sélectionne un point. Dans l’admin, contrôlez le transporteur, l’adresse ou le relais avant de préparer le colis."],
    ["9. Avis clients", "Après connexion, un client peut choisir une note de 1 à 5 étoiles, écrire son commentaire et cliquer sur « Publier ». L’avis est attaché à l’article consulté. Les avis sont visibles sur la fiche produit et peuvent être modérés depuis Firebase en cas de contenu inapproprié."],
    ["10. Bonnes pratiques", "Après chaque création, vérifiez l’article dans la boutique. Avant une expédition, contrôlez l’adresse, le relais, le poids et le suivi. Faites une commande test après une modification importante. Pour un article ou une catégorie temporairement indisponible, utilisez l’œil pour masquer plutôt que la poubelle. Les prix de livraison dépendent des méthodes activées dans Sendcloud."],
  ];
  return <section className="p-8 border border-stone-900 bg-stone-950 space-y-6"><h2 className="font-serif text-2xl text-[#C4A77D]">Guide complet de l’administration</h2><p className="text-sm text-stone-400">Ce guide explique le fonctionnement de chaque onglet et le parcours recommandé.</p>{sections.map(([title, text]) => <article key={title} className="border-b border-stone-800 pb-4"><h3 className="text-[#C4A77D] uppercase text-sm mb-2">{title}</h3><p className="text-sm text-stone-300 leading-relaxed">{text}</p></article>)}</section>;
}
